### ISSUE TITLE
你好，有没有EFR Connect软件

### ISSUE THREAD

**Issue by sms-wyt** [iot-lorawan/esp32-ota-ble#1]

**Comment by iot-lorawan** [comment]
Hi,
    efr connect app可以从这里下载，https://github.com/SiliconLabs/EFRConnect-android/releases

**Comment by sms-wyt** [comment]
谢谢！我用erf connect 2.32版本的软件，选择gbl文件时，发现名称一定要blinkbinESP.gbl才可用识别。我ESP32测试可用正常OTA，ESP32本身支持修改MTU到517，不过软件的MTU最大只能为250，耗费时间会多不少。

**Comment by iot-lorawan** [comment]
因siliconlabs的这个蓝牙app软件原来是配合该家的蓝牙芯片用的，该家蓝牙芯片的升级固件文件类型是.gbl所以文件名需要以.gbl类型，另app本身限定mtu size是244，所以每包都是按244来传。目前该app有提供源码参考，可以自己在源码上来修改如上的这些限定。源码地址：https://github.com/SiliconLabs/EFRConnect-android

**Comment by sms-wyt** [comment]
谢谢回答。不过没有搞过安卓，搭建安卓开发环境也不简单吧。
