### ISSUE TITLE
OTA失败，请问什么原因，谢谢

### ISSUE THREAD

**Issue by heyangxinmei** [iot-lorawan/esp32-ota-ble#2]
![image](https://user-images.githubusercontent.com/29226337/142571726-1cb8992d-c636-42e4-afe8-9ee87ec58f80.png)

I (47170) GATTS_TABLE_DEMO: GATT_WRITE_EVT, handle = 44, value len = 256, value :
I (47170) GATTS_TABLE_DEMO: ota-data = 0
I (47230) GATTS_TABLE_DEMO: GATT_WRITE_EVT, handle = 42, value len = 1, value :
I (47230) GATTS_TABLE_DEMO: ota-control = 3
I (47230) GATTS_TABLE_DEMO: ======endota======
I (47230) esp_image: segment 0: paddr=00190020 vaddr=3c020020 size=05e88h ( 24200) map
E (47240) esp_image: invalid segment length 0x47c8f147
E (47250) GATTS_TABLE_DEMO: Image validation failed, image is corrupted
E (47250) GATTS_TABLE_DEMO: esp_ota_end failed (ESP_ERR_OTA_VALIDATE_FAILED)!
I (47260) esp_image: segment 0: paddr=00190020 vaddr=3c020020 size=05e88h ( 24200) map
E (47270) esp_image: invalid segment length 0x47c8f147
E (47280) GATTS_TABLE_DEMO: esp_ota_set_boot_partition failed (ESP_ERR_OTA_VALIDATE_FAILED)!
I (47290) GATTS_TABLE_DEMO: Prepare to restart system!

**Comment by iot-lorawan** [comment]
Hi.
             要升级的固件大小多大，留意看下esp的ota分区是否够存放要升级的固件大小。

**Comment by heyangxinmei** [comment]
我直接用你提供的例程，升级的都不行，也不知道是哪的问题。升级的程序已经传输完成了，执行esp_ota_end(update_handle);函数返回错误ESP_ERR_OTA_VALIDATE_FAILED；网上搜索结果如下：
![image](https://user-images.githubusercontent.com/29226337/142597635-d01c3ae6-9a82-4d29-9a40-a16a9d4786c6.png)

**Comment by iot-lorawan** [comment]
Hi.
      看下板子是不是c3型号的，烧写前可以先擦除你板子的已有分区设定，idf.py erase_flash

**Comment by heyangxinmei** [comment]
![image](https://user-images.githubusercontent.com/29226337/142711947-8a6b746b-e8e6-49d9-98b4-6f2825da50ad.png)
![image](https://user-images.githubusercontent.com/29226337/142711985-31161eb4-70d8-4d9f-8482-ed0d97911641.png)
第一张图的升级信息是安卓手机，MTU是244，第二张图是苹果手机的496，苹果手机升级不成功。安卓的手机可以。

**Comment by heyangxinmei** [comment]
![image](https://user-images.githubusercontent.com/29226337/142712103-43b5a63d-32d8-4b8c-8491-043ac91ff85f.png)
苹果手机发送的长度与芯片接收的长度不一致，所以就出现升级错误了。我把MTU改为最大250：esp_ble_gatt_set_local_mtu(250);苹果手机也可以了。

**Comment by iot-lorawan** [comment]
你好.
        不好意思，我这边没iPhone，用的是安卓手机测的。蓝牙mtu可以由设备和手机进行协商，可以把esp32的mtu设定成244（esp32可以通过修改这个宏定义ESP_GATT_MAX_MTU_SIZE），这样苹果手机就会按设备的这个244长度来发送。

**Comment by heyangxinmei** [comment]
找到问题所在了，根本问题这个地方定义的是一个uint8_t ，所以大于256的数据包会发生错误，改为uint16_t应该就可以了。 uint8_t length = param->write.len;
![image](https://user-images.githubusercontent.com/29226337/142712403-22e6634e-84f5-4684-850e-7defbaa6eab8.png)
非常感谢你的例程。

**Comment by iot-lorawan** [comment]
Hi.
    很高兴这份例程对你有用，关于iPhone的这个修复建议可以是pull到这个仓库里，到时合并进去。

**Comment by heyangxinmei** [comment]
还是麻烦你上传吧，我这边下载的压缩包。

**Comment by heyangxinmei** [comment]
安卓版本的手机升级完成后出现这个提示，是什么问题啊？谢谢

**Comment by iot-lorawan** [comment]
Hi，
     升级失败提示什么，之前好像你那是安卓手机可以iphone手机才不行？

**Comment by heyangxinmei** [comment]
苹果手机可以升级。Android手机也可以升级完成，但是就是弹出附件里的界面。应该是软件权限的问题。

**Comment by iot-lorawan** [comment]
你好，
       不好意思，附件好像看不到。我这边是使用华为手机测试目前都正常，你那看下是否有其他安卓手机试试。

**Comment by heyangxinmei** [comment]
你好，能否添加下微信或者QQ。聊天方便。 我微信号：18003952500  QQ号：421020145。
