### ISSUE TITLE
OTA完成了，但程序无法运行

### ISSUE THREAD

**Issue by suhjn** [iot-lorawan/esp32-ota-ble#3]
你好！
我使用的是S3的芯片，你给的demo下载后可以正常运行，也可以通过手机的APP进行OTA操作，OTA烧录的例程是乐鑫官方的blink例程编译生成的blink.bin(改为gbl后缀了)文件，OTA烧录之后系统无法启动，是我哪一步操作不对吗？
![144212](https://user-images.githubusercontent.com/64453357/174964230-0dc8e7e7-2849-4d72-8bd9-c071235fe781.png)

**Comment by iot-lorawan** [comment]
你好，
        blink.bin有事先在s3板子上确认可以运行吗

**Comment by suhjn** [comment]
blink.bin在S3板子上可以运行的，也试过许多次，情况一样的

**Comment by iot-lorawan** [comment]
你好，
       我这边没有s3板子，目前看不出哪里问题，目前ble ota主要是通过ble通道把固件写到flash上，实际ota固件切换时有esp的ota组件实现。看下是否验证下esp ota组件是否有s3支持了，或者方便的话直接idf例用http验证下esp ota组件是否能在s3上上升级新固件。

**Comment by suhjn** [comment]
你好！问题解决了，是配置文件的问题，使用C3和S3芯片的配置文件差别还是蛮大的。把配置文件替换成S3的，然后改一下里面的分区表和蓝牙的配置，问题成功解决了。谢谢你的指导！

**Comment by iot-lorawan** [comment]
好的，相互学习
